# Generated by Django 4.2.4 on 2023-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_num', models.TextField()),
                ('locker', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reception_date', models.DateField()),
                ('packaged_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delicery_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Ready to ship'), ('2', 'Shipped'), ('3', 'Delivered at office')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=8)),
                ('locker', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('op', 'Operator'), ('client', 'Client')], max_length=10)),
            ],
        ),
    ]
